# RIPE Database objects for AS215520, read from the RPSL templates in
# infra/network/irr/ so that the human-readable files stay the single
# source of truth. Lines starting with '#' are comments; continuation lines
# are not used in these templates.
locals {
  irr_dir = "${path.module}/../../../network/irr"

  rpsl = {
    as_set  = file("${local.irr_dir}/as-set-AS215520-AS-ALL.rpsl")
    aut_num = file("${local.irr_dir}/aut-num-AS215520.rpsl")
  }

  attrs = {
    for name, text in local.rpsl : name => [
      for line in split("\n", text) :
      {
        name  = regex("^([a-z0-9-]+):\\s*(.*)$", line)[0]
        value = trimspace(regex("^([a-z0-9-]+):\\s*(.*)$", line)[1])
      }
      # The provider supplies "source" itself (from the database setting);
      # sending it too yields "Multiple source: found". created and
      # last-modified are generated by the RIPE DB on every write.
      if trimspace(line) != "" && !startswith(line, "#") && !startswith(line, "source:") && !startswith(line, "created:") && !startswith(line, "last-modified:")
    ]
  }
}

# Create the as-set first: the aut-num export lines reference it.
# The provider stores an object's attributes WITHOUT the class attribute
# (class/value carry it), so the lists below skip the first RPSL line.
resource "ripedb_object" "as_set" {
  class      = local.attrs.as_set[0].name
  value      = local.attrs.as_set[0].value
  attributes = slice(local.attrs.as_set, 1, length(local.attrs.as_set))
  # The RIPE DB validates on every write (and in the REST dry run); the
  # provider's local schema lags the live templates, so it is skipped.
  skip_validation = true
}

resource "ripedb_object" "aut_num" {
  class      = local.attrs.aut_num[0].name
  value      = local.attrs.aut_num[0].value
  attributes = slice(local.attrs.aut_num, 1, length(local.attrs.aut_num))
  # RIPE NCC-managed attributes (sponsoring-org, status, mnt-by
  # RIPE-NCC-END-MNT, created, last-modified) are submitted verbatim; the
  # local validator does not know all of them.
  skip_validation = true

  depends_on = [ripedb_object.as_set]
}

output "as_set" { value = "${local.attrs.as_set[0].name}:${local.attrs.as_set[0].value}" }
output "aut_num" { value = "${local.attrs.aut_num[0].name}:${local.attrs.aut_num[0].value}" }
